In [1]:
import pandas as pd

# Задание 1

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [188]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
movie_ratings = movies.merge(ratings, on='movieId', how='left')
movie_ratings.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09

In [150]:
def rating_type(data):
    a = 0
    if data['rating'] <= 2:
        a = 'Низкий рейтинг'
    elif data['rating'] <= 4:
        a = 'Средний рейтинг'     
    elif data['rating'] <= 5:
        a = 'Высокий рейтинг' 
    else:
        a = 'Не определено'
    return a

In [17]:
movie_ratings ['rating category'] = movie_ratings.apply(rating_type, axis=1)
movie_ratings.head(30)

,movieId,title,genres,userId,rating,timestamp,rating category
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08,Средний рейтинг
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08,Средний рейтинг
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09,Высокий рейтинг
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09,Средний рейтинг
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09,Высокий рейтинг
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.5,1.455210e+09,Средний рейтинг
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,4.0,9.657056e+08,Средний рейтинг
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21.0,3.5,1.407619e+09,Средний рейтинг
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27.0,3.0,9.626853e+08,Средний рейтинг
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31.0,5.0,8.504666e+08,Высокий рейтинг
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32.0,3.0,8.567361e+08,Средний рейтинг
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33.0,3.0,9.396474e+08,Средний рейтинг
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40.0,5.0,8.320590e+08,Высокий рейтинг
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,5.0,8.489940e+08,Высокий рейтинг
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44.0,3.0,8.692519e+08,Средний рейтинг
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45.0,4.0,9.511702e+08,Средний рейтинг
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46.0,5.0,8.347879e+08,Высокий рейтинг
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,50.0,3.0,1.514238e+09,Средний рейтинг
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,54.0,3.0,8.302473e+08,Средний рейтинг
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,57.0,5.0,9.657960e+08,Высокий рейтинг
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,63.0,5.0,1.443200e+09,Высокий рейтинг
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,64.0,4.0,1.161520e+09,Средний рейтинг
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,66.0,4.0,1.104644e+09,Средний рейтинг
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,68.0,2.5,1.158531e+09,Средний рейтинг
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,71.0,5.0,8.647379e+08,Высокий рейтинг
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73.0,4.5,1.464196e+09,Высокий рейтинг
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,76.0,0.5,1.439166e+09,Низкий рейтинг
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,78.0,4.0,1.252575e+09,Средний рейтинг
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,82.0,2.5,1.084468e+09,Средний рейтинг
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86.0,4.0,1.344083e+09,Средний рейтинг

# Задание 2

Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [28]:
keywords = pd.read_csv('keywords.csv')
keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [58]:
def region_class(query):
    geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
    }
    
    for i in geo_data.items():
        for x in i[1]:
            if x in query:
                return i[0]
    return 'undefined'

In [63]:
keywords['region'] = keywords['keyword'].apply(region_class)

In [64]:
keywords['region'].value_counts()

undefined         99253
Центр               387
Северо-Запад        266
Дальний Восток       94
Name: region, dtype: int64

# Задание 3 (бонусное)

Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [178]:
movie_ratings.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09

In [191]:
# В переменную years запишите список из всех годов с 1950 по 2010.

years = list(range(1950,2011))

# Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. 

def production_year(data):
    for y in years:
        if str(y) in data:
            return y
    return 1900

movie_ratings['year'] = movie_ratings['title'].apply(production_year)   # added year column
movie_ratings.groupby('year')['rating'].mean().sort_values(ascending = False)  # sorted average rating

year
1957    4.039535
1954    4.009191
1962    3.969466
1952    3.953125
1972    3.944293
          ...
2000    3.398922
2005    3.359976
1992    3.353555
1997    3.347241
1996    3.335329
Name: rating, Length: 62, dtype: float64

In [187]:
# same task using regular expressions

import re
def year_def(data):
    pattern = '\((\d{4})\)'
    x = re.search(pattern, data)
    if x:
        return int(x.group(1))
    else:
        return 1900
    
movie_ratings['year'] = movie_ratings['title'].apply(year_def)  # added year column
movie_ratings_1950_2010 = movie_ratings[(movie_ratings.year >= 1950)&(movie_ratings.year <= 2010)]  # filtered 1950-2010

movie_ratings_1950_2010.groupby('year')['rating'].mean().sort_values(ascending = False)  # sorted average rating

% time

year
1957    4.039535
1954    4.009191
1962    3.969466
1952    3.953125
1964    3.940160
          ...
2000    3.398899
2005    3.359888
1992    3.354943
1997    3.347241
1996    3.335329
Name: rating, Length: 61, dtype: float64